[[redirects]]
  from = "/home"
  to = "/"

[[redirects]]
  from = "/blog/my-post.php"
  to = "/blog/my-post"

[[redirects]]
  from = "/news"
  to = "/blog"

[[redirects]]
  from = "/cuties"
  to = "https://www.petsofnetlify.com"

[[redirects]]
  from = "/authors/c%C3%A9line"
  to = "/authors/about-c%C3%A9line"

[[headers]]
  for = "/templates/index.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/templates/index2.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
